### ISSUE TITLE
 Error: Unable to call `modelClass["getClassName"]`, which is undefined or falsey

### ISSUE THREAD

**Issue by dev-mansonthomas** [asyncapi/java-spring-cloud-stream-template#201] opened 2021-10-25 17:06 UTC
#### Describe the bug

while generating a Spring Cloud Stream project with the follwing spec : 

[IntegrationTask.yaml.txt](https://github.com/asyncapi/java-spring-cloud-stream-template/files/7412260/IntegrationTask.yaml.txt)

using the following command line : 

ag IntegrationTask.yaml @asyncapi/java-spring-cloud-stream-template -o IntegrationTaskProject #-p server=production

Note : this is in the https://www.asyncapi.com/tools/generator example, and it doesn't work with Spring Cloud Stream (didn't test the other generators)
#-p server=production

Full exception : 

```
Template render error: (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/java-spring-cloud-stream-template/template/src/main/java/$$everySchema$$.java) [Line 2, Column 43]
  Error: Unable to call `modelClass["getClassName"]`, which is undefined or falsey
    at Object._prettifyError (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/lib.js:36:11)
    at /usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:563:19
    at eval (eval at _compile (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:46:11)
    at /usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:613:9
    at Template.root [as rootRenderFunc] (eval at _compile (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:854:3)
    at Template.getExported (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:611:10)
    at eval (eval at _compile (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:45:5)
    at Environment.getTemplate (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:279:9)
    at eval (eval at _compile (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:43:5)
    at eval (eval at _compile (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:25:1)
    at fn (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/a-sync-waterfall/index.js:26:24)
    at /usr/local/lib/node_modules/@asyncapi/generator/node_modules/a-sync-waterfall/index.js:66:22
    at executeSync (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/a-sync-waterfall/index.js:8:15)
    at /usr/local/lib/node_modules/@asyncapi/generator/node_modules/a-sync-waterfall/index.js:65:11
    at eval (eval at _compile (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:20:1)
    at /usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:571:11
```

#### Expected behavior
No exception, and a full project generated.

**Comment by CameronRushton** [comment] 2021-11-01 03:01
Thanks for the descriptive report! This seems to be a duplicate of #194, however, lets continue discussion here.

**Closed** 2022-01-05 16:52 UTC
Labels: bug
