### ISSUE TITLE
Generation of code for json type array fails with Cannot read property "type" of null error

### ISSUE THREAD

**Issue by ShriKiniSol** [asyncapi/java-spring-cloud-stream-template#102] opened 2021-04-26 06:54 UTC
The code generator fails to generate the code for the yaml which has json schema with type as array

It throws error 'Cannot read property "type" of null'.

Attaching the screenshot for the error for reference.
.[image](https://user-images.githubusercontent.com/76467399/116040759-ffb49380-a69e-11eb-91ab-c231763438f8.png)

#### Expected behavior
It should allow to generate the code for the type array.

**Comment by derberg** [comment] 2021-04-26 09:05
@ShriKiniSol hey, can you please provide the asyncapi document that you use for generation? also pass `--debug` flag to generator and share logs again? Thank you  🙏🏼

**Comment by ShriKiniSol** [comment] 2021-04-27 07:29
@derberg 
Please find attached the error logs and the yaml file used.


[Error_Logs.txt](https://github.com/asyncapi/java-spring-cloud-stream-template/files/6382697/Error_Logs.txt)
[Channel_API_Gateway_v1_1.yaml.zip](https://github.com/asyncapi/java-spring-cloud-stream-template/files/6382699/Channel_API_Gateway_v1_1.yaml.zip)

**Comment by derberg** [comment] 2021-04-27 07:51
@ShriKiniSol I hope you don't mind but can you please share those in the comment, formatted with markdown as code? For security reasons we would not like to open any files, especially zips. Thanks in advance 🙏🏼

**Comment by thrillstone** [comment] 2021-06-01 03:41
This sounds like a duplicate of https://github.com/asyncapi/java-spring-cloud-stream-template/issues/92

**Comment by damaru-inc** [comment] 2021-06-04 12:59
I checked, it's not a dup of #92.

**Comment by damaru-inc** [comment] 2021-06-06 13:47
There are numerous problems with the input file. First of all, array properties need to have an 'items' property that describes the array elements. You've used the name 'details' instead. I tried to fix that, but under what should be 'items' you have:

- type: object
  properties:

there should be no dash before 'type.'

**Comment by damaru-inc** [comment] 2021-06-08 19:34
@ShriKiniSol in light of my previous comment, can I please close this issue?

**Comment by damaru-inc** [comment] 2021-06-17 14:23
Didn't hear back, I'm closing this.

**Closed by damaru-inc** 2021-06-17 14:23 UTC
Labels: bug
